export const productDisplaySection = [
    {
      imgURL: "",
      productTitle: "floral-print long-sleeve T-shirt",
      totalPrice: "$227",
      offerPrice: "$6,457",
      color: ["red", "black", "Silver"],
      size: ["xs", "s", "M", "L", "XL", "XXL", "XXXL"],
      brand: ["Addidas", "Nike", "Polo"],
      metirial: ["Cotton", "Polyster", "Lenin"],
      careRecommendation: ["Machine Wash", "Hand Wash"],
      deliveryAddress: ["Plot no: 22, Secundrabad, Hyderabad"],
      return: ["Non Refundable", "Refundable"],
    },
    {
      imgURL:
        "https://cdn-images.farfetch-contents.com/21/98/54/78/21985478_51856589_480.jpg",
      productTitle: "1990-2000s lipstick-print cotton shirt",
      totalPrice: "$4,127",
      offerPrice: "$6,457",
      color: ["red", "black", "Silver"],
      size: ["xs", "s", "M", "L", "XL", "XXL", "XXXL"],
      brand: ["Addidas", "Nike", "Polo"],
      metirial: ["Cotton", "Polyster", "Lenin"],
      careRecommendation: ["Machine Wash", "Hand Wash"],
      deliveryAddress: ["Plot no: 22, Secundrabad, Hyderabad"],
      return: ["Non Refundable", "Refundable"],
    },
    {
      imgURL:
        "https://cdn-images.farfetch-contents.com/19/73/21/08/19732108_44715453_480.jpg",
      productTitle: "",
      totalPrice: "",
      offerPrice: "$6,457",
      color: ["red", "black", "Silver"],
      size: ["xs", "s", "M", "L", "XL", "XXL", "XXXL"],
      brand: ["Addidas", "Nike", "Polo"],
      metirial: ["Cotton", "Polyster", "Lenin"],
      careRecommendation: ["Machine Wash", "Hand Wash"],
      deliveryAddress: ["Plot no: 22, Secundrabad, Hyderabad"],
      return: ["Non Refundable", "Refundable"],
    },
    {
      id: "",
      imgURL:
        "https://cdn-images.farfetch-contents.com/22/75/80/88/22758088_53121234_480.jpg",
      productTitle: "floral-print long-sleeve T-shirt",
      totalPrice: "$227",
      offerPrice: "$6,457",
      color: ["red", "black", "Silver"],
      size: ["xs", "s", "M", "L", "XL", "XXL", "XXXL"],
      brand: ["Addidas", "Nike", "Polo"],
      metirial: ["Cotton", "Polyster", "Lenin"],
      careRecommendation: ["Machine Wash", "Hand Wash"],
      deliveryAddress: ["Plot no: 22, Secundrabad, Hyderabad"],
      return: ["Non Refundable", "Refundable"],
    },
    {
      imgURL:
        "https://cdn-images.farfetch-contents.com/21/98/54/78/21985478_51856589_480.jpg",
      productTitle: "1990-2000s lipstick-print cotton shirt",
      totalPrice: "$4,127",
      offerPrice: "$6,457",
      color: ["red", "black", "Silver"],
      size: ["xs", "s", "M", "L", "XL", "XXL", "XXXL"],
      brand: ["Addidas", "Nike", "Polo"],
      metirial: ["Cotton", "Polyster", "Lenin"],
      careRecommendation: ["Machine Wash", "Hand Wash"],
      deliveryAddress: ["Plot no: 22, Secundrabad, Hyderabad"],
      return: ["Non Refundable", "Refundable"],
    },
    {
      imgURL:
        "https://cdn-images.farfetch-contents.com/19/73/21/08/19732108_44715453_480.jpg",
      productTitle: "floral-print organic cotton shirt",
      totalPrice: "$577",
      offerPrice: "$6,457",
      color: ["red", "black", "Silver"],
      size: ["xs", "s", "M", "L", "XL", "XXL", "XXXL"],
      brand: ["Addidas", "Nike", "Polo"],
      metirial: ["Cotton", "Polyster", "Lenin"],
      careRecommendation: ["Machine Wash", "Hand Wash"],
      deliveryAddress: ["Plot no: 22, Secundrabad, Hyderabad"],
      return: ["Non Refundable", "Refundable"],
    },
    {
      imgURL: "",
      productTitle: "floral-print long-sleeve T-shirt",
      totalPrice: "$227",
      offerPrice: "$6,457",
      color: ["red", "black", "Silver"],
      size: ["xs", "s", "M", "L", "XL", "XXL", "XXXL"],
      brand: ["Addidas", "Nike", "Polo"],
      metirial: ["Cotton", "Polyster", "Lenin"],
      careRecommendation: ["Machine Wash", "Hand Wash"],
      deliveryAddress: ["Plot no: 22, Secundrabad, Hyderabad"],
      return: ["Non Refundable", "Refundable"],
    },
    {
      imgURL:
        "https://cdn-images.farfetch-contents.com/21/98/54/78/21985478_51856589_480.jpg",
      productTitle: "1990-2000s lipstick-print cotton shirt",
      totalPrice: "$4,127",
      offerPrice: "$6,457",
      color: ["red", "black", "Silver"],
      size: ["xs", "s", "M", "L", "XL", "XXL", "XXXL"],
      brand: ["Addidas", "Nike", "Polo"],
      metirial: ["Cotton", "Polyster", "Lenin"],
      careRecommendation: ["Machine Wash", "Hand Wash"],
      deliveryAddress: ["Plot no: 22, Secundrabad, Hyderabad"],
      return: ["Non Refundable", "Refundable"],
    },
    {
      imgURL:
        "https://cdn-images.farfetch-contents.com/19/73/21/08/19732108_44715453_480.jpg",
      productTitle: "",
      totalPrice: "",
      offerPrice: "$6,457",
      color: ["red", "black", "Silver"],
      size: ["xs", "s", "M", "L", "XL", "XXL", "XXXL"],
      brand: ["Addidas", "Nike", "Polo"],
      metirial: ["Cotton", "Polyster", "Lenin"],
      careRecommendation: ["Machine Wash", "Hand Wash"],
      deliveryAddress: ["Plot no: 22, Secundrabad, Hyderabad"],
      return: ["Non Refundable", "Refundable"],
    },
    {
      imgURL:
        "https://cdn-images.farfetch-contents.com/22/75/80/88/22758088_53121234_480.jpg",
      productTitle: "floral-print long-sleeve T-shirt",
      totalPrice: "$227",
      offerPrice: "$6,457",
      color: ["red", "black", "Silver"],
      size: ["xs", "s", "M", "L", "XL", "XXL", "XXXL"],
      brand: ["Addidas", "Nike", "Polo"],
      metirial: ["Cotton", "Polyster", "Lenin"],
      careRecommendation: ["Machine Wash", "Hand Wash"],
      deliveryAddress: ["Plot no: 22, Secundrabad, Hyderabad"],
      return: ["Non Refundable", "Refundable"],
    },
    {
      imgURL:
        "https://cdn-images.farfetch-contents.com/21/98/54/78/21985478_51856589_480.jpg",
      productTitle: "1990-2000s lipstick-print cotton shirt",
      totalPrice: "$4,127",
      offerPrice: "$6,457",
      color: ["red", "black", "Silver"],
      size: ["xs", "s", "M", "L", "XL", "XXL", "XXXL"],
      brand: ["Addidas", "Nike", "Polo"],
      metirial: ["Cotton", "Polyster", "Lenin"],
      careRecommendation: ["Machine Wash", "Hand Wash"],
      deliveryAddress: ["Plot no: 22, Secundrabad, Hyderabad"],
      return: ["Non Refundable", "Refundable"],
    },
    {
      imgURL:
        "https://cdn-images.farfetch-contents.com/19/73/21/08/19732108_44715453_480.jpg",
      productTitle: "floral-print organic cotton shirt",
      totalPrice: "$577",
      offerPrice: "$6,457",
      color: ["red", "black", "Silver"],
      size: ["xs", "s", "M", "L", "XL", "XXL", "XXXL"],
      brand: ["Addidas", "Nike", "Polo"],
      metirial: ["Cotton", "Polyster", "Lenin"],
      careRecommendation: ["Machine Wash", "Hand Wash"],
      deliveryAddress: ["Plot no: 22, Secundrabad, Hyderabad"],
      return: ["Non Refundable", "Refundable"],
    },
  ];